MvcProjeKampi/Controllers/AdminWriterController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidatonRules;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using EntityLayer.EntityFramework;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PagedList.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminWriterController : Controller
    {
        WriterManager wr = new WriterManager(new EFWriterDal());
        public ActionResult Index(int page=1)
        {
            //var getres = wr.GetList();
            var getres = wr.GetList().ToPagedList(page,6);
            return View(getres);
        }

        [HttpGet]
        public ActionResult WriterAdd()
        {
            return View();
        }
        [HttpPost]
        public ActionResult WriterAdd(Writer w)
        {
            WriterValidator val = new WriterValidator();
            ValidationResult results = val.Validate(w); 
            if (results.IsValid)
            {             
                wr.WriterAdd(w);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var e in results.Errors)
                {
                    ModelState.AddModelError(e.PropertyName, e.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult WriterDelete(int id)
        {
            var del = wr.GetById(id);
            wr.WriterDelete(del);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult WriterUpdate(int id)
        {
            var up = wr.GetById(id);
            return View(up);
        }
        [HttpPost]
        public ActionResult WriterUpdate(Writer w)
        {
            wr.WriterUpdate(w);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Views/AdminWriter/Index.cshtml
@using EntityLayer.Concrete
@using PagedList;
@using PagedList.Mvc;
@model PagedList.IPagedList<Writer>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<style>
    .pagination-container{text-align:center}
</style>

<link href="~/Content/PagedList.css" rel="stylesheet" />

<a href="/AdminWriter/WriterAdd" class="btn btn-primary mb-3">Yazar Ekle</a>

<div class="card card-solid">
    <div class="card-body pb-0">
        <div class="row d-flex align-items-stretch">
            @foreach (var writer in Model)
            {
                <div class="col-12 col-sm-6 col-md-4 d-flex align-items-stretch">
                    <div class="card bg-light">
                        <div class="card-body pt-0">
                            <div class="row">
                                <div class="col-7 pt-3">
                                    <h2 class="lead"><b>@writer.WriterName @writer.WriterSurname</b></h2>
                                    <p class="text-muted text-sm"><b>Hakkında: </b>@writer.WriterAbout</p>
                                    <ul class="ml-4 mb-0 fa-ul text-muted">
                                        <li class="small"><span class="fa-li"><i class="fas fa-mail-bulk"></i></span>@writer.WriterMail</li>
                                    </ul>
                                </div>
                                <div class="col-5 text-center">
                                    <img src="/Content/AdminPanel/dist/img/user1-128x128.jpg" alt="" class="img-circle img-fluid">
                                </div>
                            </div>
                        </div>
                        <div class="card-footer">
                            <div class="text-right">
                                <a href="/AdminWriter/WriterDelete/@writer.WriterId" class="btn btn-danger btn-sm">
                                    Sil
                                </a>
                                <a href="/AdminWriter/WriterUpdate/@writer.WriterId" class="btn btn-sm btn-warning">
                                    Düzenle
                                </a>
                                <a href="#" class="btn btn-sm btn-primary">
                                    Yazıları
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>

</div>


@Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page }))

MvcProjeKampi/Views/AdminWriter/WriterAdd.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using(Html.BeginForm("WriterAdd","AdminWriter",FormMethod.Post,new {enctype="multipart/form-data"}))
{
    <div class="form-group">
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(w => w.WriterName, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(w => w.WriterSurname, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Hakkında")
        @Html.TextBoxFor(w => w.WriterAbout, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Resmi")
        <input type="file" name="WriterImage" />
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(w => w.WriterMail, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(w => w.WriterPassaword, new { @class = "form-control" })

    </div>
    <button class="btn btn-info">Kaydet</button>
}

MvcProjeKampi/Views/AdminWriter/WriterUpdate.cshtml
@model EntityLayer.Concrete.Writer
@{
    ViewBag.Title = "WriterUpdate";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("WriterUpdate", "AdminWriter", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Id")
        @Html.TextBoxFor(w => w.WriterId, new { @class = "form-control"})
        <br />
        @Html.Label("Yazar Adı")
        @Html.TextBoxFor(w => w.WriterName, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Soyadı")
        @Html.TextBoxFor(w => w.WriterSurname, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Hakkında")
        @Html.TextBoxFor(w => w.WriterAbout, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Resmi")
        <input type="file" name="WriterImage" />
        <br />
        @Html.Label("Yazar Mail")
        @Html.TextBoxFor(w => w.WriterMail, new { @class = "form-control" })
        <br />
        @Html.Label("Yazar Şifre")
        @Html.TextBoxFor(w => w.WriterPassaword, new { @class = "form-control" })

    </div>
    <button class="btn btn-info">Güncelle</button>
}