MvcProjeKampi/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidatonRules;
using EntityLayer.Concrete;
using EntityLayer.EntityFramework;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EFCategoryDal());   
        public ActionResult Index()
        {
            var result = cm.GetList();
            return View(result);
        }

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        public ActionResult DeleteCategory(int id)
        {
            var categoryvalue = cm.GetById(id);
            cm.CategoryDelete(categoryvalue);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var catval = cm.GetById(id);
            return View(catval);
        }
        [HttpPost]
        public ActionResult EditCategory(Category c)
        {
            cm.CategoryUpdate(c);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using(Html.BeginForm("AddCategory","AdminCategory",FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x=>x.CategoryName , new {@class="form-control" })
        @Html.ValidationMessageFor(x=>x.CategoryName)
        <br /><br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x=>x.CategoryDescription, new {@class="form-control" })
        @Html.ValidationMessageFor(x=>x.CategoryDescription)

    </div>
    <button class="btn btn-info">Kaydet</button>
}

MvcProjeKampi/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category
@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Id")
        @Html.TextBoxFor(x => x.CategoryId, new { @class = "form-control" })
        <br />
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
        <br /><br />
        @Html.Label("Kategori Açıklaması")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    </div>
    <button class="btn btn-info">Güncelle</button>

}

MvcProjeKampi/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

 <a href="/AdminCategory/AddCategory" class="btn btn-primary mb-3">Kategori Ekle</a>

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Kategori Adı</th>
            <th>Sil</th>
            <th>Güncelle</th>
            <th>Başlıklar</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryId</th>
            <td>@item.CategoryName</td>
            <td style="text-align:center"><a href="/AdminCategory/DeleteCategory/@item.CategoryId" class="btn btn-danger">Sil</a></td>
            <td style="text-align:center"><a href="/AdminCategory/EditCategory/@item.CategoryId" class="btn btn-warning">Güncelle</a></td>
            <td style="text-align:center"><a href="#" class="btn btn-primary">Başlıklar</a></td>
        </tr>
    }
</table>