MvcProjeKampi/Controllers/AdminHeadingController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidatonRules;
using DataAccessLayer.Concrete;
using EntityLayer.Concrete;
using EntityLayer.EntityFramework;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProjeKampi.Controllers
{
    public class AdminHeadingController : Controller
    {

        HeadingManager hm = new HeadingManager(new EFHeadingDal());
        Context c = new Context();
        public ActionResult Index()
        {
            var result = hm.GetList();
            return View(result);
        }
        [HttpGet]
        public ActionResult HeadingAdd()
        {
            List<SelectListItem> dgr1 = (from i in c.Categories.ToList()
                                        select new SelectListItem
                                        {
                                            Text = i.CategoryName,
                                            Value = i.CategoryId.ToString()
                                        }).ToList();
            List<SelectListItem> dgr2 = (from w in c.Writers.ToList()
                                         select new SelectListItem
                                         {
                                             Text = w.WriterName+" "+w.WriterSurname,
                                             Value = w.WriterId.ToString()
                                         }).ToList();
            ViewBag.dgr1 = dgr1;
            ViewBag.dgr2 = dgr2;
            return View();
        }
        [HttpPost]
        public ActionResult HeadingAdd(Heading heading)
        {
            HeadingValidator val = new HeadingValidator();
            ValidationResult result = val.Validate(heading);
            if(result.IsValid)
            {
                hm.HeadingAdd(heading);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var h in result.Errors)
                {
                    ModelState.AddModelError(h.PropertyName, h.ErrorMessage);
                }
            }
            return View();
        }
        public ActionResult HeadingDelete(int id)
        {
            var del = hm.GetById(id);
            hm.HeadingDelete(del);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult HeadingUpdate(int id)
        {
            var upd = hm.GetById(id);
            return View(upd);
        }
        [HttpPost]
        public ActionResult HeadingUpdate(Heading heading)
        {
            hm.HeadingUpdate(heading);
            return RedirectToAction("Index");
        }
    }
}

MvcProjeKampi/Views/AdminHeading/HeadingAdd.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "HeadingAdd";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


@using (Html.BeginForm("HeadingAdd", "AdminHeading", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Başlık Adı")
        @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
        <br />
        @Html.Label("Başlık Tarihi")
        @Html.TextBoxFor(model => model.HeadingDate,new { @type = "date" ,@class="form-control"})
        <br />
        @Html.Label("Kategori Adı")
        @Html.DropDownListFor(x=>x.Category.CategoryName,(List<SelectListItem>)ViewBag.dgr1,new {@class="form-control"})
        <br />
        @Html.Label("Yazar Adı")
        @Html.DropDownListFor(x => x.Writer.WriterName, (List<SelectListItem>)ViewBag.dgr2, new {@class="form-control"})
    </div>
    <button class="btn btn-info">Kaydet</button>

}

MvcProjeKampi/Views/AdminHeading/Index.cshtml
@using EntityLayer.Concrete;
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



<a href="/AdminHeading/HeadingAdd" class="btn btn-primary mb-3">Başlık Ekle</a>

<table class="table table-bordered table-hover">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Başlık Adı</th>
            <th>Başlık Tarihi</th>
            <th>Kategori Adı</th>
            <th>Sil</th>
            <th>Güncelle</th>
        </tr>
    </thead>
    @foreach (var h in Model)
    {
        <tr>
            <th>@h.HeadingId</th>
            <td>@h.HeadingName</td>
            <td>@h.HeadingDate</td>
            <td>@h.Category.CategoryName</td>
            <td style="text-align:center"><a href="/AdminHeading/HeadingDelete/@h.HeadingId" class="btn btn-danger">Sil</a></td>
            <td style="text-align:center"><a href="/AdminHeading/HeadingUpdate/@h.HeadingId" class="btn btn-warning">Güncelle</a></td>
        </tr>
    }
</table>